baseURL = 'https://DanielBrett.github.io/Digital-Scholarship-at-Brock-University'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'blist'
metaDataFormat = "yaml"

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2021 - Danie is Great.  Mwahahahaha · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"